[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello-world"
path = "src/main.rs"

[[bin]]
name = "numbers"
path = "src/basic_type/numbers.rs"

[[bin]]
name = "binding_var"
path = "src/binding_var/binding_var.rs"